name: Build Platforms Core

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]
    
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Linux
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build
        cmake --version
        ninja --version

    - name: Build And Install Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -G "Ninja" 

        cmake --build build -j2
       
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Linx newton
        path: |
          ./lib/libndNewton.lib
    
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Setup MacOS
  #     shell: bash
  #     run: |
  #       sudo apt update
  #       sudo apt install -y cmake ninja-build
  #       cmake --version
  #       ninja --version

  #   - name: Build Newton
  #     shell: bash
  #     run: |
  #       cd newton-3.14
  #       cmake \
  #           -S . -B build \
  #           -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
  #           -DCMAKE_BUILD_TYPE=Release \
  #           -G "Ninja" 

  #       cmake --build build -j2
  
  #   - name: Archive results
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: Linx newton
  #       path: |
  #         ./lib/libndSolverAvx2.so
  #         ./lib/libndNewton.so

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Windows
      shell: bash
      run: |
        choco install ninja cmake
        cmake --version
        ninja --version

    - name: Build Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -G "Visual Studio 17 2022" -A x64 \

        cmake --build build -j2
        
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Windows newton
        path: |
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgCore\Debug\dgCore_d.lib
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgPhysics\Debug\dgPhysics_d.lib
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgNewton\Debug\newton_d.lib
