name: Build Platforms Core

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]
    
jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Android
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build
        cmake --version
        ninja --version

    - name: Build Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DCMAKE_VS_PLATFORM_NAME=ARM64 \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX:PATH=/tmp/newton \
            -G "Ninja" 

        cmake --build build -j2
       
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Android newton
        path: |
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgCore.a
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgPhysics.a
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libnewton.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Linux
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build
        cmake --version
        ninja --version

    - name: Build Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX:PATH=/tmp/newton \
            -G "Ninja" 

        cmake --build build -j2
       
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Linx newton
        path: |
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgCore.a
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgPhysics.a
          /home/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libnewton.a
    
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup MacOS
      shell: bash
      run: |
        brew install cmake ninja
        cmake --version
        ninja --version

    - name: Build Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX:PATH=/tmp/newton \
            -G "Ninja" 

        cmake --build build -j2
  
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Macos newton
        path: |
          /Users/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgCore.a
          /Users/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libdgPhysics.a
          /Users/runner/work/newton-dynamics/newton-dynamics/newton-3.14/build/lib/libnewton.a

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Windows
      shell: bash
      run: |
        choco install ninja cmake
        cmake --version
        ninja --version

    - name: Build Newton
      shell: bash
      run: |
        cd newton-3.14
        cmake \
            -S . -B build \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_INSTALL_PREFIX:PATH=out

        cmake --build build -j2
        
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: Windows newton
        path: |
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgCore\Debug\dgCore_d.lib
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgPhysics\Debug\dgPhysics_d.lib
          D:\a\newton-dynamics\newton-dynamics\newton-3.14\build\sdk\dgNewton\Debug\newton_d.lib
